name: Test and Deploy
on: [push]
jobs:
  Test-and-Deploy-App:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install app dependencies
          run: pip install -r ./app/requirements.txt
        - name: Run tests
          run: py.test ./app/tests/test_app.py
        - uses: actions/setup-node@v3
          with:
            node-version: 14
        - name: Install infra dependencies
          run: npm install -g aws-cdk
        - name: Deploy
          run: cdk --version

